---
- name: Audio System Overlay
  hosts: localhost
  connection: local

  handlers:
    - name: Load Handlers
      include: "handlers/main.yml"

  pre_tasks:
    - name: Load Variables
      include_vars:
        dir: "vars"
    - name: Enforce OSX Versions
      include_tasks: "tasks/pre_install.yml"

  roles:
    - elliotweiser.osx-command-line-tools
    - geerlingguy.mac.homebrew
    - osx_provisioner.homebrew_retry
    - osx_provisioner.downloader

  post_tasks:
    - name: Run Post Install Tasks
      include_tasks: "tasks/post_install.yml"
