---
- name: Base System Dock Customization
  hosts: localhost
  connection: local

  handlers:
    - name: Load Handlers
      include: "handlers/main.yml"

  pre_tasks:
    - name: Load Variables
      include_vars:
        dir: "vars"
    - name: Enforce OSX Versions
      include_tasks: "tasks/pre_install.yml"

  roles:
    - elliotweiser.osx-command-line-tools
    - geerlingguy.mac.homebrew
    - osx_provisioner.homebrew_retry
    - osx_provisioner.homeshick
    - osx_provisioner.clamav
    - osx_provisioner.asdf
    - osx_provisioner.symlinks
    - osx_provisioner.downloader
    - niall_byrne.ansible_role_osx_defaults

  post_tasks:
    - name: Run Post Install Tasks
      include_tasks: "tasks/post_install.yml"
