---
- name: Am I running on Mac OS X?
  fail:
    msg: Target host is not running Mac OS X
  when: ansible_distribution != 'MacOSX'

- name: Is this version of Mac OS X supported?
  fail:
    msg: Target host is not running a compatible Mac OS X version
  when: ansible_distribution_version is version(minimum_osx_version, '<')
