---
- name: Configure fstab
  include_tasks: "post_install/fstab.yml"

- name: Perform System Preferences
  include_tasks: "post_install/mas.yml"

- name: Perform Python Customizations
  include_tasks: "post_install/python.yml"

- name: Perform Dock Content
  include_tasks: "post_install/dock_content.yml"

- name: Configure Preferences
  include_tasks: "post_install/preferences.yml"

- name: Configure Shell
  include_tasks: "post_install/shell.yml"
